version: "3.8"

services:
  db:
    image: mariadb:10.9.8
    container_name: nadomofone_db
    restart: on-failure
    volumes:
      - ./.volumes/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nadomofone}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nadomofone}
      - MYSQL_USER=${MYSQL_USER:-nadomofone}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nadomofone}
    networks:
      - nadomofone
    ports:
      - "127.0.0.1:${MARIADB_PORT:-33060}:3306"

  redis:
    image: redis:7.0-bookworm
    container_name: nadomofone_redis
    restart: on-failure
    volumes:
      - ./.volumes/redis:/data
    networks:
      - nadomofone
    ports:
      - "127.0.0.1:${REDIS_PORT:-63790}:6379"

networks:
  nadomofone:
    name: nadomofone_net
    external: false
