# Generated by Django 3.2.4 on 2024-05-21 12:38

import core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='phone_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.files.upload_to, verbose_name='Логотип Телефон'),
        ),
        migrations.AddField(
            model_name='setup',
            name='telegram_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.files.upload_to, verbose_name='Логотип Telegram'),
        ),
        migrations.AddField(
            model_name='setup',
            name='whatsapp_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.files.upload_to, verbose_name='Логотип WhatsApp'),
        ),
    ]
