# Generated by Django 3.2.4 on 2022-03-24 09:54

import core.files
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjuster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_mounting', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата за монтаж, руб')),
                ('cost_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата за замену, руб')),
                ('cost_repair', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата за ремонт, руб')),
                ('cost_dismantling', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата за демонтаж, руб')),
                ('coord_x', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ширина')),
                ('coord_y', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Монтажник',
                'verbose_name_plural': 'Монтажники',
            },
        ),
        migrations.CreateModel(
            name='AdjusterTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Монтаж новой конструкции'), (1, 'Замена'), (2, 'Ремонт стенда'), (3, 'Демонтаж стенда'), (4, 'Осмотр')], verbose_name='Вид работы')),
                ('date', models.DateField(verbose_name='Дата задачи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('adjuster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjuster.adjuster', verbose_name='Монтажник')),
            ],
            options={
                'verbose_name': 'Монтажник',
                'verbose_name_plural': 'Монтажники',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdjusterTaskSurface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('adjustertask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjuster.adjustertask', verbose_name='Задача')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.surface', verbose_name='Поверхность')),
            ],
            options={
                'verbose_name': 'Поверхность (дом, адрес) для задачи',
                'verbose_name_plural': 'Поверхности (дома, адреса) для задачи',
            },
        ),
        migrations.CreateModel(
            name='SurfacePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата фотографии')),
                ('image', models.ImageField(upload_to=core.files.surfacephoto_upload, verbose_name='Изображение')),
                ('is_broken', models.BooleanField(default=False, verbose_name='Поломка')),
                ('adjuster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adjuster.adjuster', verbose_name='Монтажник')),
                ('porch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.porch', verbose_name='Подъезд')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdjusterTaskSurfacePorch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('complete', models.BooleanField(default=False, verbose_name='Работы выполнены')),
                ('adjustertasksurface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjuster.adjustertasksurface', verbose_name='Поверхность для задачи')),
                ('porch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.porch', verbose_name='Подъезд поверхности для задачи')),
            ],
            options={
                'verbose_name': 'Подъезд по задаче',
                'verbose_name_plural': 'Подъезды па задаче',
            },
        ),
    ]
