# Generated by Django 3.2.4 on 2022-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjuster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuster',
            name='cost_view',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата за осмотр, руб'),
        ),
    ]
